import { Component, computed, inject, output } from '@angular/core';

import { CityResult } from '../../services/location.service';
import { LanguageService } from '../../services/language.service';
import { DestinationCard, RichDestination } from '../destination-card/destination-card';

@Component({
  selector: 'app-popular-destinations',
  imports: [DestinationCard],
  templateUrl: './popular-destinations.html',
  styleUrl: './popular-destinations.scss',
})
export class PopularDestinations {
  readonly language = inject(LanguageService);
  readonly selected = output<CityResult>();

  readonly destinations = computed<RichDestination[]>(() => this.language.language() === 'en' ? this.enDestinations : this.ptDestinations);

  private readonly ptDestinations: RichDestination[] = [
    {
      type: 'city',
      id: 'popular-luanda',
      name: 'Luanda',
      city: 'Luanda',
      country: 'Angola',
      country_code: 'AO',
      region: 'Luanda',
      latitude: -8.839,
      longitude: 13.2894,
      population: 2571861,
      image: 'https://commons.wikimedia.org/wiki/Special:Redirect/file/Luanda%20Skyline%20-%20Angola%202015.jpg?width=900',
      tagline: 'Costa Atlântica, energia urbana e dias quentes para explorar.',
      climate: '28 C · sol costeiro',
      restaurants: ['Lookal', 'Kook', 'Embarcadouro'],
      attractions: ['Ilha do Cabo', 'Fortaleza', 'Marginal'],
      budget: 'AOA 95k/dia',
    },
    {
      type: 'city',
      id: 'popular-benguela',
      name: 'Benguela',
      city: 'Benguela',
      country: 'Angola',
      country_code: 'AO',
      region: 'Benguela',
      latitude: -12.5763,
      longitude: 13.4055,
      population: 623777,
      image: 'https://images.unsplash.com/photo-1519046904884-53103b34b206?auto=format&fit=crop&w=900&q=82',
      tagline: 'Praias tranquilas, arquitetura colonial e mar calmo para descansar.',
      climate: '27 C · brisa atlântica',
      restaurants: ['Baia Azul', 'Kalunga', 'Restinga'],
      attractions: ['Baía Azul', 'Praia Morena', 'Lobito'],
      budget: 'AOA 78k/dia',
    },
    {
      type: 'city',
      id: 'popular-lubango',
      name: 'Lubango',
      city: 'Lubango',
      country: 'Angola',
      country_code: 'AO',
      region: 'Huila',
      latitude: -14.9172,
      longitude: 13.4925,
      population: 776249,
      image: 'https://images.unsplash.com/photo-1516026672322-bc52d61a55d5?auto=format&fit=crop&w=900&q=82',
      tagline: 'Serra, miradouros e paisagens perfeitas para aventura.',
      climate: '22 C · montanha',
      restaurants: ['Casablanca', 'Kimbo do Soba', 'Nossa Terra'],
      attractions: ['Serra da Leba', 'Cristo Rei', 'Tundavala'],
      budget: 'AOA 70k/dia',
    },
    {
      type: 'city',
      id: 'popular-namibe',
      name: 'Namibe',
      city: 'Namibe',
      country: 'Angola',
      country_code: 'AO',
      region: 'Namibe',
      latitude: -15.1961,
      longitude: 12.1522,
      population: 132900,
      image: 'https://images.unsplash.com/photo-1509316785289-025f5b846b35?auto=format&fit=crop&w=900&q=82',
      tagline: 'Deserto, oceano e rotas fotográficas de outro mundo.',
      climate: '24 C · seco',
      restaurants: ['Esplanada Flamingo', 'Ponto Final', 'O Navegante'],
      attractions: ['Deserto do Namibe', 'Tômbwa', 'Arco'],
      budget: 'AOA 82k/dia',
    },
    {
      type: 'city',
      id: 'popular-cabo-ledo',
      name: 'Cabo Ledo',
      city: 'Cabo Ledo',
      country: 'Angola',
      country_code: 'AO',
      region: 'Bengo',
      latitude: -9.6717,
      longitude: 13.2326,
      population: null,
      image: 'https://images.unsplash.com/photo-1500375592092-40eb2168fd21?auto=format&fit=crop&w=900&q=82',
      tagline: 'Ondas longas, falésias e praia para fins de semana memoráveis.',
      climate: '29 C · praia',
      restaurants: ['Carpe Diem', 'Resort local', 'Quiosques da praia'],
      attractions: ['Praia de Cabo Ledo', 'Miradouro', 'Surf point'],
      budget: 'AOA 65k/dia',
    },
    {
      type: 'city',
      id: 'popular-cape-town',
      name: 'Cape Town',
      city: 'Cape Town',
      country: 'South Africa',
      country_code: 'ZA',
      region: 'Western Cape',
      latitude: -33.9249,
      longitude: 18.4241,
      population: 433688,
      image: 'https://images.unsplash.com/photo-1580060839134-75a5edca2e99?auto=format&fit=crop&w=900&q=82',
      tagline: 'Montanha, vinhos, praias e uma cena gastronómica global.',
      climate: '21 C · mediterrâneo',
      restaurants: ['Fyn', 'Kloof Street House', 'Harbour House'],
      attractions: ['Table Mountain', 'V&A Waterfront', 'Camps Bay'],
      budget: 'USD 95/dia',
    },
    {
      type: 'city',
      id: 'popular-zanzibar',
      name: 'Zanzibar',
      city: 'Zanzibar',
      country: 'Tanzania',
      country_code: 'TZ',
      region: 'Zanzibar Urban/West',
      latitude: -6.1659,
      longitude: 39.2026,
      population: 501459,
      image: 'https://images.unsplash.com/photo-1540202404-a2f29016b523?auto=format&fit=crop&w=900&q=82',
      tagline: 'Águas turquesa, Stone Town e sabores do Índico.',
      climate: '30 C · tropical',
      restaurants: ['The Rock', 'Lukmaan', 'Emerson Spice'],
      attractions: ['Stone Town', 'Nungwi', 'Prison Island'],
      budget: 'USD 110/dia',
    },
    {
      type: 'city',
      id: 'popular-marrakech',
      name: 'Marrakech',
      city: 'Marrakech',
      country: 'Morocco',
      country_code: 'MA',
      region: 'Marrakech-Safi',
      latitude: 31.6295,
      longitude: -7.9811,
      population: 928850,
      image: 'https://images.unsplash.com/photo-1539020140153-e479b8c22e70?auto=format&fit=crop&w=900&q=82',
      tagline: 'Souks, riads, jardins e noites vibrantes no Magrebe.',
      climate: '26 C · seco',
      restaurants: ['Nomad', 'Le Jardin', 'Al Fassia'],
      attractions: ['Medina', 'Jardin Majorelle', 'Bahia Palace'],
      budget: 'USD 85/dia',
    },
    {
      type: 'city',
      id: 'popular-cairo',
      name: 'Cairo',
      city: 'Cairo',
      country: 'Egypt',
      country_code: 'EG',
      region: 'Cairo Governorate',
      latitude: 30.0444,
      longitude: 31.2357,
      population: 10100000,
      image: 'https://images.unsplash.com/photo-1572252009286-268acec5ca0a?auto=format&fit=crop&w=900&q=82',
      tagline: 'História monumental, museus e roteiros pelo Nilo.',
      climate: '29 C · desértico',
      restaurants: ['Abou El Sid', 'Zooba', 'Naguib Mahfouz'],
      attractions: ['Pirâmides de Gizé', 'Museu Egípcio', 'Khan el-Khalili'],
      budget: 'USD 75/dia',
    },
  ];

  private readonly enDestinations: RichDestination[] = this.ptDestinations.map((destination) => ({
    ...destination,
    tagline: this.translateTagline(destination.id),
    climate: destination.climate.replace('sol costeiro', 'coastal sun').replace('brisa atlântica', 'Atlantic breeze').replace('montanha', 'mountain').replace('praia', 'beach').replace('seco', 'dry').replace('mediterrâneo', 'Mediterranean').replace('tropical', 'tropical').replace('desértico', 'desert'),
    budget: destination.budget.replace('/dia', '/day'),
  }));

  private translateTagline(id: string | number | null): string {
    const taglines: Record<string, string> = {
      'popular-luanda': 'Atlantic coast, urban energy and warm days to explore.',
      'popular-benguela': 'Quiet beaches, colonial architecture and calm water for resting.',
      'popular-lubango': 'Mountains, viewpoints and landscapes made for adventure.',
      'popular-namibe': 'Desert, ocean and striking photo routes.',
      'popular-cabo-ledo': 'Long waves, cliffs and a beach made for weekends.',
      'popular-cape-town': 'Mountain, wine, beaches and a global food scene.',
      'popular-zanzibar': 'Turquoise water, Stone Town and Indian Ocean flavors.',
      'popular-marrakech': 'Souks, riads, gardens and vibrant nights in the Maghreb.',
      'popular-cairo': 'Monumental history, museums and Nile routes.',
    };

    return taglines[String(id)] || '';
  }
}
